### ISSUE TITLE
Error: 'not' is not a valid parameter name

### ISSUE THREAD

**Issue by mrkeil** [seifertm/hypothesis-workshop#2]
Hi Michael, I set up my local copy of the code for the workshop exactly as instructed in the readme.

During pytest, the following error showed up:
> tests/test_04_web_api.py - ValueError: 'not' is not a valid parameter name

A quick google search directed me to this issue
tiangolo/fastapi#5048

The solution that worked for me was to **upgrade the constraint for pydantic to 1.10.1** and re-run the installation. 

Hoping this might help other participants if they have the same issue during the workshop.

**Comment by DanielSzoska** [comment]
Another solution: Use Python 3.10 for the venv.

**Comment by seifertm** [comment]
Thanks for reporting this!
I updated the dependencies on the weekend and something must have gone wrong.

I regenerated the constraints, addressed some deprecation warnings, and tested with Python3.8, 3.11, and 3.12. It should be fine now.
